CREATE TABLE craft-digest_beers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    brewery_name TEXT NOT NULL,
    brewery_location TEXT,
    tasting_notes TEXT,
    abv NUMERIC NOT NULL,
    rating NUMERIC NOT NULL
);